name: Scheduled Repo Sync

on:
  schedule:
    - cron: '*/5 * * * *' # Täglich um Mitternacht
  workflow_dispatch: # Ermöglicht manuelles Triggern

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync main with upstream

    steps:
    - name: Checkout target repo
      uses: actions/checkout@v4
      with:
        ref: main # Oder der entsprechende Name Ihres Default-Branches
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Sync Upstream
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
      with:
        target_repo_token: ${{ secrets.GITHUB_TOKEN }}
        upstream_repository: derlemue/villa-kunterbunt
        upstream_branch: main
        target_branch: main
        test_mode: false
