name: Sync Fork Caller

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

# Globale Berechtigungen f√ºr das Token des Callers
permissions:
  contents: write
  workflows: write
<<<<<<< Updated upstream

jobs:
  call-sync:
=======
  pull-requests: write

jobs:
  call-sync-fork:
    # ...und stellen sicher, dass der Job sie auch wirklich anwenden darf
    permissions:
      contents: write
      workflows: write
      pull-requests: write
>>>>>>> Stashed changes
    uses: lemueIO/.github/.github/workflows/central-sync-logic.yml@main
    with:
      upstream_url: "https://github.com/derlemue/villa-kunterbunt.git"
    secrets: inherit
